baseurl = "http://www.example.com" # Hostname (and path) to the root.
title = "Yusuke Ishimi" # Site title.
theme = "coder-portfolio" # Set the theme.
languagecode = "en" # The site’s language code used to generate RSS.
defaultcontentlanguage = "en" # The default content language.

paginate = 20 # Default number of pages per page in pagination.

pygmentsstyle = "b2" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.
pygmentsUseClasses = true # new add

disqusShortname = "yourdiscussshortname" # Enable or disable Disqus.

[params] # theme parameters
    author = "Yusuke Ishimi" # Author's name.
    info = "WEB AND APPS ENGINEER" # Author's job title or info.
    description = "Yusuke Ishimi's personal website" # Site description.
    keywords = "blog,developer,personal" # Site keywords.
    avatarurl = "images/avatar.jpg" # Contain the path of the optionnal avatar in the static folder.

    footercontent = "Enter a text here." # Add footer content
    fixedbarContent = "Do you want to know me more private?→" # Add fixedbar content
    fixedbarContentAfter = "Thank You! Please share it if you like it→" # Add fixedbar content after click

    # Whether you want to hide copyright and credits in the footer.
    hideCredits = false
    hideCopyright = false

    # Custom CSS
    custom_css = []

    # Alignment of Mobile Menu items
    itemscentered = true

    # RTL support
    rtl = false

    # Bottom sns share
    snsShare = true # new add
    # Popular sns share
    # if you want add sns. please message!
    enableTwitterShare = true  # new add
    enableFacebookShare = true # new add
    enableHatenaShare = false   # new add
    enableLineShare = false     # new add
    enableLinkedInShare = true # new add

    thumbnail = "images/tn.png" # default sns thumbnail

    # Multilanguage mode
    langseparator = "|" # Separates menus from language selectors when site is multilingual.

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/nightlord189"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 3
    url = "https://www.linkedin.com/in/nightlord189/"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "posts"
[[menu.main]]
    name = "About"
    weight = 2
    url = "about"

[languages]
    [languages.en]
        languagename = "English" # The language name to be displayed in the selector.
        title = "Alexey Buravov"

        # You can configure the theme parameter for each language. 
        [languages.en.params]
        author = "Alexey Buravov"
        info = "Software developer"
        description = "Yusuke Ishimi's personal website"
        keywords = "blog,developer,personal"

        [languages.en.menu] # It is possible to change the menu too.

        [[languages.en.menu.main]]
        name = "About"
        weight = 1.0
        url = "about"

        [[languages.en.menu.main]]
        name = "Blog"
        weight = 2.0
        url = "posts"

        [[languages.en.menu.main]]
        name = "Projects"
        weight = 3.0
        url = "projects"

        [[languages.en.menu.main]]
        name = "Contacts"
        weight = 4.0
        url = "contact"

        [[languages.en.menu.main]]
        name = "CV"
        weight = 1.5
        url = "cv"

    [languages.ru]
        languagename = "Russian"
        title = "Алексей Буравов"

        [languages.ru.params]
            author = "Алексей Буравов"
            description = "Персональная страничка"
            keywords = "blog,developer,software"
            info = "Разработчик"

        [languages.ru.menu]

            [[languages.ru.menu.main]]
            name = "О себе"
            weight = 1.0
            url = "ru/about"

            [[languages.ru.menu.main]]
            name = "Блог"
            weight = 2.0
            url = "ru/posts"

            [[languages.ru.menu.main]]
            name = "Проекты"
            weight = 3.0
            url = "projects"

            [[languages.ru.menu.main]]
            name = "Контакты"
            weight = 4.0
            url = "contact"

            [[languages.ru.menu.main]]
            name = "Резюме"
            weight = 1.5
            url = "cv"